# Generated by Django 5.0.6 on 2024-09-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_customuser_city_customuser_is_nid_varified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=150),
        ),
    ]
