# Generated by Django 5.0.6 on 2024-09-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_alter_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Changesmadetoyouraccount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Informationonnewtrade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Marketingandpromooffers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='updatred_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='updatred_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
