# Generated by Django 5.0.6 on 2024-09-25 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0005_customuser_changesmadetoyouraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='seen_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('photo', models.FileField(upload_to='massage')),
                ('seen_status', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatred_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentder', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
