# Generated by Django 5.0.6 on 2024-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0006_notifications_seen_status_massege'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='binenceaccountno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
