# Generated by Django 5.0.6 on 2024-09-28 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0007_customuser_binenceaccountno'),
    ]

    operations = [
        migrations.AddField(
            model_name='massege',
            name='connect',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MyRefeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_boll_fiel', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='references_user', to=settings.AUTH_USER_MODEL)),
                ('team_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_boll_fiel', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('team_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
