# Generated by Django 5.0.6 on 2024-10-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0008_massege_connect_myrefelist_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicControlScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw1', models.BooleanField(default=False)),
                ('sw2', models.BooleanField(default=False)),
                ('sw3', models.BooleanField(default=False)),
                ('sw4', models.BooleanField(default=True)),
                ('sw5', models.BooleanField(default=True)),
                ('sw6', models.BooleanField(default=True)),
                ('sks', models.CharField(max_length=150)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
