# Generated by Django 5.0.6 on 2024-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0009_dynamiccontrolscheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='sks1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='sks2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='sks3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='sks4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='time1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='time2',
            field=models.IntegerField(default=5),
        ),
    ]
