# Generated by Django 5.0.6 on 2024-10-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0010_dynamiccontrolscheduling_sks1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MytodaysIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomefee', models.FloatField(default=0.0)),
                ('charge', models.FloatField(default=0.0)),
                ('sw1', models.BooleanField(default=False)),
                ('income_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
