# Generated by Django 5.0.6 on 2024-10-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0011_mytodaysincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='diposite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='getreward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='imvest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='inv_persentice',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='manage_fund',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='payout_charge',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='dynamiccontrolscheduling',
            name='reference_persentice',
            field=models.FloatField(default=5.0),
        ),
    ]
