# Generated by Django 5.0.6 on 2024-10-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0012_dynamiccontrolscheduling_diposite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
