# Generated by Django 5.0.6 on 2024-09-26 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Method', models.CharField(default='USDT', max_length=100)),
                ('Txn_Details', models.CharField(max_length=250)),
                ('deposite_ammount', models.IntegerField(default=25.0)),
                ('Charges', models.IntegerField(default=0.0)),
                ('aproved_status', models.BooleanField(default=False)),
                ('txn_id_binenc', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
