# Generated by Django 5.0.6 on 2024-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0002_deposite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='income_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='walet_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='Charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='deposite_ammount',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='invastments',
            name='Charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invastments',
            name='inv_ammount',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='Charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_ammount',
            field=models.FloatField(default=25.0),
        ),
        migrations.CreateModel(
            name='WaletShate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Method', models.CharField(default='USDT', max_length=100)),
                ('Txn_Details', models.CharField(max_length=250)),
                ('share_ammount', models.FloatField(default=0.0)),
                ('Charges', models.FloatField(default=0.0)),
                ('aproved_status', models.BooleanField(default=False)),
                ('txn_id_binenc', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waletshare', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
