# Generated by Django 5.0.6 on 2024-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0003_alter_bankaccount_bank_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waletshate',
            name='main_account',
            field=models.BooleanField(default=False),
        ),
    ]
