# Generated by Django 5.0.6 on 2024-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0004_waletshate_main_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
