# Generated by Django 5.0.6 on 2024-09-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0005_payout_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='binence_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
