# Generated by Django 5.0.6 on 2024-09-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0006_payout_binence_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='invastments',
            name='BN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BanckManagement.bankaccount'),
        ),
        migrations.AddField(
            model_name='payout',
            name='BN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BanckManagement.bankaccount'),
        ),
    ]
