# Generated by Django 5.0.6 on 2024-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0010_alter_invastments_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepackeges',
            name='DailyProfit',
        ),
        migrations.AddField(
            model_name='tradepackeges',
            name='bonus',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='tradepackeges',
            name='range_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradepackeges',
            name='range_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
