# Generated by Django 5.0.6 on 2024-09-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0011_remove_tradepackeges_dailyprofit_tradepackeges_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepackeges',
            name='Plan',
        ),
        migrations.RemoveField(
            model_name='tradepackeges',
            name='extrachar',
        ),
        migrations.AddField(
            model_name='tradepackeges',
            name='Plan_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradepackeges',
            name='Plan_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradepackeges',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
