# Generated by Django 5.0.6 on 2024-10-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0013_getreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Name', models.CharField(max_length=25)),
                ('PayAddress', models.CharField(max_length=250)),
                ('Qrcode', models.ImageField(upload_to='qrimage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
