# Generated by Django 5.0.6 on 2024-10-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0014_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='Payment_Name',
            field=models.CharField(max_length=100),
        ),
    ]
