# Generated by Django 5.0.6 on 2024-10-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0015_alter_paymentmethod_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
