# Generated by Django 5.0.6 on 2024-10-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0016_paymentmethod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='seenstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='Payment_Method',
            field=models.CharField(max_length=250),
        ),
    ]
