# Generated by Django 5.0.6 on 2024-10-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0017_deposite_seenstatus_alter_deposite_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='payadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BanckManagement.paymentmethod'),
        ),
    ]
