# Generated by Django 5.0.6 on 2024-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanckManagement', '0019_remove_deposite_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='removed_status',
            field=models.BooleanField(default=False),
        ),
    ]
